---
version: 1.1.x.{build}
branches:
  only:
    - master
    - release
environment:
  matrix:
    -
      RUBY_VERSION: 24-x64
      CHECK: syntax lint metadata_lint check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop
    -
      PUPPET_GEM_VERSION: ~> 5.0
      RUBY_VERSION: 24
      CHECK: parallel_spec
    -
      PUPPET_GEM_VERSION: ~> 5.0
      RUBY_VERSION: 24-x64
      CHECK: parallel_spec
    -
      PUPPET_GEM_VERSION: ~> 6.0
      RUBY_VERSION: 25
      CHECK: parallel_spec
    -
      PUPPET_GEM_VERSION: ~> 6.0
      RUBY_VERSION: 25-x64
      CHECK: parallel_spec
matrix:
  fast_finish: true
